import type { AwsWafClassification } from "./ClassificationRequest/AwsWafClassification";
import type { FunCaptchaClassification } from "./ClassificationRequest/FunCaptchaClassification";
import type { HCaptchaClassification } from "./ClassificationRequest/HCaptchaClassification";
import type { ImageToTextTask } from "./ClassificationRequest/ImageToTextTask";
import type { ReCaptchaV2Classification } from "./ClassificationRequest/ReCaptchaV2Classification";
import { AntiAkamaiBMPTask } from "./TokenRequest/AntiAkamaiBMPTask";
import type { AntiAkamaiPowTask } from "./TokenRequest/AntiAkamaiPowTask";
import type { AntiAkamaiSensorTask } from "./TokenRequest/AntiAkamaiSensorTask";
import type { AntiAkamaiWebTask } from "./TokenRequest/AntiAkamaiWebTask";
import type { AntiAwsWafTask } from "./TokenRequest/AntiAwsWafTask";
import type { AntiAwsWafTaskProxyLess } from "./TokenRequest/AntiAwsWafTaskProxyLess";
import type { AntiCloudflareChallengeTask } from "./TokenRequest/AntiCloudflareChallengeTask";
import type { AntiCloudflareTurnstileTask } from "./TokenRequest/AntiCloudflareTurnstileTask";
import type { AntiCyberSiAraTask } from "./TokenRequest/AntiCyberSiAraTask";
import type { AntiCyberSiAraTaskProxyLess } from "./TokenRequest/AntiCyberSiAraTaskProxyLess";
import type { AntiImpervaTask } from "./TokenRequest/AntiImpervaTask";
import type { AntiImpervaTaskProxyLess } from "./TokenRequest/AntiImpervaTaskProxyLess";
import type { DataDomeSliderTask } from "./TokenRequest/DataDomeSliderTask";
import type { FunCaptchaTaskProxyLess } from "./TokenRequest/FunCaptchaTaskProxyLess";
import { GeeTestTask } from "./TokenRequest/GeeTestTask";
import { GeeTestTaskProxyLess } from "./TokenRequest/GeeTestTaskProxyLess";
import type { GeeTestV3Task } from "./TokenRequest/GeeTestV3Task";
import type { GeeTestV3TaskProxyLess } from "./TokenRequest/GeeTestV3TaskProxyLess";
import type { GeeTestV4Task } from "./TokenRequest/GeeTestV4Task";
import type { GeeTestV4TaskProxyLess } from "./TokenRequest/GeeTestV4TaskProxyLess";
import type { HCaptchaTask } from "./TokenRequest/HCaptchaTask";
import type { HCaptchaTaskProxyLess } from "./TokenRequest/HCaptchaTaskProxyLess";
import type { MtCaptchaTask } from "./TokenRequest/MtCaptchaTask";
import type { MtCaptchaTaskProxyLess } from "./TokenRequest/MtCaptchaTaskProxyLess";
import type { ReCaptchaV2EnterpriseTask } from "./TokenRequest/ReCaptchaV2EnterpriseTask";
import type { ReCaptchaV2EnterpriseTaskProxyLess } from "./TokenRequest/ReCaptchaV2EnterpriseTaskProxyLess";
import type { ReCaptchaV2Task } from "./TokenRequest/ReCaptchaV2Task";
import type { ReCaptchaV2TaskProxyLess } from "./TokenRequest/ReCaptchaV2TaskProxyLess";
import type { ReCaptchaV3EnterpriseTask } from "./TokenRequest/ReCaptchaV3EnterpriseTask";
import type { ReCaptchaV3EnterpriseTaskProxyLess } from "./TokenRequest/ReCaptchaV3EnterpriseTaskProxyLess";
import type { ReCaptchaV3M1TaskProxyLess } from "./TokenRequest/ReCaptchaV3M1TaskProxyLess";
import type { ReCaptchaV3Task } from "./TokenRequest/ReCaptchaV3Task";
import type { ReCaptchaV3TaskProxyLess } from "./TokenRequest/ReCaptchaV3TaskProxyLess";
import type { BaseTask } from "./_BaseTaskRequest";

export type Requests = AntiAkamaiBMPTask | AntiAkamaiPowTask | AntiAkamaiSensorTask | AntiAkamaiWebTask | AntiAwsWafTask | AntiAwsWafTaskProxyLess | AntiCloudflareChallengeTask | AntiCloudflareTurnstileTask | AntiCyberSiAraTask | AntiCyberSiAraTaskProxyLess | AntiImpervaTask | AntiImpervaTaskProxyLess | AwsWafClassification | BaseTask | DataDomeSliderTask | FunCaptchaClassification | FunCaptchaTaskProxyLess | GeeTestTask | GeeTestTaskProxyLess | GeeTestV3Task | GeeTestV3TaskProxyLess | GeeTestV4Task | GeeTestV4TaskProxyLess | HCaptchaClassification | HCaptchaTask | HCaptchaTaskProxyLess | ImageToTextTask | MtCaptchaTask | MtCaptchaTaskProxyLess | ReCaptchaV2Classification | ReCaptchaV2EnterpriseTask | ReCaptchaV2EnterpriseTaskProxyLess | ReCaptchaV2Task | ReCaptchaV2TaskProxyLess | ReCaptchaV3EnterpriseTask | ReCaptchaV3EnterpriseTaskProxyLess | ReCaptchaV3M1TaskProxyLess | ReCaptchaV3Task | ReCaptchaV3TaskProxyLess;

export * from "./ClassificationRequest/index";

export * from "./TokenRequest/index";